version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - shared_net
    restart: unless-stopped

networks:
  shared_net:
    external: true
